### ISSUE TITLE
Camera view is stopped when broadcast is stopped on Android

### ISSUE THREAD

**Issue by JesseDunlap** [medlmobileenterprises/react-native-wowza-gocoder#11]
My team and I have been working with react-native-wowza-gocoder with great success, but we encountered some strange behavior on Android that I was hoping to get some clarification on. Our app has the ability to start and stop a broadcast, but the GoCoder component is never removed or re-added to the page as it is the main screen of the app.

On iOS, this works fine, and we've had no issues. However, on Android, we've noticed that after stopping the broadcast (e.g. setting the `isBroadcasting` property to `false`) the camera view becomes unresponsive and as far as I know we aren't able to start the broadcast again.

We forked the repo and tracked the issue down to line `218` of `BroadcastView.java`, where the `stopCamera` method is being called. This in turn calls the `stopPreview` method on the `WZCameraView`. Removing this call fixes the issue for our purposes but--as mentioned--I'm curious about why this was here in the first place. It does appear that the camera preview is started again on host resume, but that doesn't apply well to our use case, or to most use cases I would imagine.

Any clarification/insight would be greatly appreciated. We are currently maintaining our own fork of react-native-wowza-gocoder but I would love to contribute some of our changes back to this project, while keeping the projects goals in mind, obviously. Thank you!

**Comment by hugo-ns** [comment]
I’m glad our react-native-wowza-gocoder has worked for you and your team.

About the issue, starting and stopping the same broadcast without leaving the broadcast screen has never been one of our uses cases. 
We initially design it for with an app where users would only use the broadcast once.
It would start when loading the broadcast screen and stop when leaving the screen, and this flow has worked for most of the use cases using the package for other apps as well.

However, what you and your team found it’s definitely an issue. Since we provide the methods to start and stop, these methods should work as intended.
I’d be more than happy to have you contributing with this fix. 

-Thank you!

**Comment by JesseDunlap** [comment]
Got it, that makes sense in that context, thanks! Yeah, if you're open to it, we can submit a pull request with some changes. The app we're using also has the need to dynamically change the broadcast name, since a user can start a new broadcast from the main screen at any time. I'd like to contribute this back to your repo as well, but we will submit it as two pull requests so you guys can decide how to proceed with pulling the changes back in.
