### ISSUE TITLE
Camera View is stuck on second run. 

### ISSUE THREAD

**Issue by AbhishekNairTnex** [medlmobileenterprises/react-native-wowza-gocoder#16]
Hi 

Firstly thanks for the wonderful library. 
We are using it to build an app that streams to wowza.
When i click a button and navigate to the screen with the broadcast view the first time, it shows the camera properly. 
but i don't start broadcast i go back to the old screen and then click on the button to go back to the screen with the broadcast view, the camera stops working 

what am i doing wrong.  what do i change to fix this issue.

**Comment by hugo-ns** [comment]
Hi there,

We have a fix for this issue. we just release an update for it.
Please trying using version 1.0.5.

Let me know if that works.

Thanks,
-Hugo

**Comment by AbhishekNairTnex** [comment]
Hi Hugo,

I have upgraded to use 1.0.5 but still face the same issue. when i go back all I see is a frozen frame of when i navigated back to the game view. 

at this point the state for broadcast is never set to true.  

find the navigation code below. 

`    if (this.state.broadcast) {
      console.log('lets stop recording.')
      this.setState({ broadcasting: false })
    } else {
      console.log('lets stop')
    }
    this.sock.close()
    this.props.navigation.navigate('GameList')`

Regards
Abhishek

**Comment by hugo-ns** [comment]
Hi Abhishek,

In What platform are you seeing this issue? 

For your case, you could probably re-render the BroadcastView when navigating back from the GameList (using a callback function, perhaps), since you are not broadcasting anything when going to the GameList the stream shouldn't be affected.

It's not the most optimal solution, but it could work for your use case.

Thanks,
-Hugo

**Comment by JesseDunlap** [comment]
Hi Abishek,

We were seeing a similar issue in #11 but I would assume the fixes we contributed back should be included if you are running the latest version of the code. One way to see what's happening (and how we eventually identified what was going on) would be to set a break point at line 76 of `BroadcastManager.m` (for iOS) or line 52 in `BroadcastManager.java` (for Android).

It's worth noting that the issue we were having was only present on Android, and was caused by the camera view being stopped when the broadcast was stopped.

Hope this helps!

**Comment by AbhishekNairTnex** [comment]
Hi Hugo and Jesse,

Yes we have updated to the latest build. We are facing this issue on Android currently. We have not yet build the app on iOS. That will be once the poc we are completing is confirmed by the client. 

I will check both your comments and thanks for the help

regards
Abhishek
