### ISSUE TITLE
Unable to release app while using this package

### ISSUE THREAD

**Issue by bendellarocco** [medlmobileenterprises/react-native-wowza-gocoder#21]
When trying to validate my app to release a beta to the app store I have given errors pertaining to wowza.  

Xcode version: 9.0 (9A235) 
React Native Version: 0.44.0

<img width="696" alt="screen shot 2017-10-24 at 10 52 17 pm" src="https://user-images.githubusercontent.com/9866222/31978231-5ec3d8d6-b90e-11e7-87fc-9ae5f7f69820.png">

**Comment by hugo-ns** [comment]
The Wowza GoCoder SDK for iOS contains support for x86 architecture, in order to submit your app you need to add a build script to strip the unnecessary code from non-supported architectures in the store.

Please follow the steps in the section "Add the Wowza GoCoder SDK framework to your project" item 7, on the following website.

https://www.wowza.com/docs/how-to-install-gocoder-sdk-for-ios

**Comment by bendellarocco** [comment]
This resolved the issue.  Maybe add this to a troubleshooting section of the read me?
