### ISSUE TITLE
Getting cam,rec,flash icon with grey background screen only.

### ISSUE THREAD

**Issue by NavneetSandhu** [medlmobileenterprises/react-native-wowza-gocoder#31]
Hello,

I'm getting grey screen with three icons and time,none of icon and time is working. Please help me out to achieve the video streaming via wowza gocoder. Also tell me the details to be filled under this fields:
 hostAddress: '',
    applicationName: '',
    sdkLicenseKey: '',
    username: '',
    streamName:'',
    password: '',

Thanks

**Comment by hugo-ns** [comment]
Hi,

hostAddress: '',
applicationName: '',
username: '',
streamName:'',
password: ''

These fields are related to your Wowza streaming engine You will need to set these values in order to send your stream to your Wowza Streaming server.

sdkLicenseKey: '',
This field is your Wowza GoCoder SDK license key, you must set this value in order to initialize the SDK properly.

Thanks
